
services:

  agent-0:
    image: ollama/ollama
    ports:
      - "11475:11434"
    volumes:
      - agent-0_data:/root/.ollama
      - ./shared_models:/root/.ollama/models
    

  agent-1:
    image: ollama/ollama
    ports:
      - "11476:11434"
    volumes:
      - agent-1_data:/root/.ollama
      - ./shared_models:/root/.ollama/models
    


volumes:

  agent-0_data:

  agent-1_data:
