[project]
name = "llm-agent-semantic-diffusion"
version = "0.1.0"
description = "ECE 227 Final Project that examines the impact of network structure on opinion dynamics with LLM agents."
authors = [{ name = "Henri Schulz", email = "henritschulz@gmail.com" }]
requires-python = ">=3.13, <3.14.1"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "ollama>=0.6.1,<0.7.0",
    "pydantic (>=2.12.5,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "requests (>=2.32.5,<3.0.0)",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "src",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"
